DROP TABLE IF EXISTS stock_barcodes CASCADE;
DROP TABLE IF EXISTS return_items CASCADE;
DROP TABLE IF EXISTS returns CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS bill_items CASCADE;
DROP TABLE IF EXISTS bills CASCADE;
DROP TABLE IF EXISTS batches CASCADE;
DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS medicines CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE categorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL UNIQUE,
    descripcion TEXT,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE marcas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL UNIQUE,
    descripcion TEXT,
    logo_url VARCHAR(500),
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_documento VARCHAR(30) NOT NULL,
    numero_documento VARCHAR(20) NOT NULL UNIQUE,
    razon_social VARCHAR(180),
    nombres VARCHAR(100),
    apellidos VARCHAR(100),
    correo VARCHAR(150),
    telefono VARCHAR(30),
    direccion VARCHAR(300),
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE proveedores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ruc VARCHAR(11) NOT NULL UNIQUE,
    razon_social VARCHAR(180) NOT NULL,
    nombre_contacto VARCHAR(150),
    correo VARCHAR(150),
    telefono VARCHAR(30),
    direccion VARCHAR(300),
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    correo VARCHAR(150) NOT NULL UNIQUE,
    contrasena VARCHAR(255) NOT NULL,
    rol VARCHAR(30) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP NOT NULL
);

CREATE TABLE productos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR(60) NOT NULL UNIQUE,
    nombre VARCHAR(200) NOT NULL,
    descripcion TEXT,
    categoria_id BIGINT NOT NULL,
    marca_id BIGINT NOT NULL,
    modelo VARCHAR(120),
    tipo_producto VARCHAR(20) NOT NULL,
    precio_compra NUMERIC(14,2) NOT NULL,
    precio_venta NUMERIC(14,2) NOT NULL,
    stock INTEGER NOT NULL DEFAULT 0,
    stock_minimo INTEGER NOT NULL DEFAULT 0,
    unidad_medida VARCHAR(20) NOT NULL,
    imagen_url VARCHAR(500),
    ficha_tecnica_url VARCHAR(500),
    garantia VARCHAR(120),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP NOT NULL,
    fecha_actualizacion TIMESTAMP NOT NULL,
    version BIGINT,
    CONSTRAINT fk_producto_categoria FOREIGN KEY (categoria_id) REFERENCES categorias(id),
    CONSTRAINT fk_producto_marca FOREIGN KEY (marca_id) REFERENCES marcas(id)
);

CREATE TABLE especificaciones_producto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id BIGINT NOT NULL UNIQUE,
    voltaje VARCHAR(80),
    corriente VARCHAR(80),
    potencia VARCHAR(80),
    frecuencia VARCHAR(80),
    fases INTEGER,
    grado_proteccion VARCHAR(40),
    material VARCHAR(120),
    dimensiones VARCHAR(180),
    peso NUMERIC(12,3),
    diametro VARCHAR(80),
    capacidad VARCHAR(100),
    velocidad VARCHAR(100),
    CONSTRAINT fk_especificacion_producto FOREIGN KEY (producto_id) REFERENCES productos(id) ON DELETE CASCADE
);

CREATE TABLE lotes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id BIGINT NOT NULL,
    proveedor_id BIGINT NOT NULL,
    codigo_lote VARCHAR(80) NOT NULL UNIQUE,
    cantidad INTEGER NOT NULL CHECK (cantidad > 0),
    precio_compra NUMERIC(14,2) NOT NULL,
    fecha_ingreso TIMESTAMP NOT NULL,
    observaciones TEXT,
    CONSTRAINT fk_lote_producto FOREIGN KEY (producto_id) REFERENCES productos(id),
    CONSTRAINT fk_lote_proveedor FOREIGN KEY (proveedor_id) REFERENCES proveedores(id)
);

CREATE TABLE movimientos_inventario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id BIGINT NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    cantidad INTEGER NOT NULL,
    fecha TIMESTAMP NOT NULL,
    referencia VARCHAR(100),
    usuario_id BIGINT NOT NULL,
    observaciones TEXT,
    CONSTRAINT fk_movimiento_producto FOREIGN KEY (producto_id) REFERENCES productos(id),
    CONSTRAINT fk_movimiento_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

CREATE TABLE ventas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_venta VARCHAR(50) NOT NULL UNIQUE,
    cliente_id BIGINT NOT NULL,
    vendedor_id BIGINT NOT NULL,
    fecha TIMESTAMP NOT NULL,
    subtotal NUMERIC(14,2) NOT NULL,
    impuesto NUMERIC(14,2) NOT NULL,
    descuento NUMERIC(14,2) NOT NULL,
    total NUMERIC(14,2) NOT NULL,
    metodo_pago VARCHAR(30) NOT NULL,
    estado VARCHAR(30) NOT NULL,
    observaciones VARCHAR(300),
    CONSTRAINT fk_venta_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id),
    CONSTRAINT fk_venta_vendedor FOREIGN KEY (vendedor_id) REFERENCES usuarios(id)
);

CREATE TABLE detalles_venta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id BIGINT NOT NULL,
    producto_id BIGINT NOT NULL,
    cantidad INTEGER NOT NULL CHECK (cantidad > 0),
    precio_unitario NUMERIC(14,2) NOT NULL,
    subtotal NUMERIC(14,2) NOT NULL,
    CONSTRAINT fk_detalle_venta FOREIGN KEY (venta_id) REFERENCES ventas(id) ON DELETE CASCADE,
    CONSTRAINT fk_detalle_producto FOREIGN KEY (producto_id) REFERENCES productos(id)
);

CREATE TABLE comprobantes_venta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id BIGINT NOT NULL UNIQUE,
    tipo VARCHAR(20) NOT NULL,
    numero VARCHAR(50) NOT NULL UNIQUE,
    serie VARCHAR(10) NOT NULL,
    fecha_emision TIMESTAMP NOT NULL,
    pdf_url VARCHAR(500),
    CONSTRAINT fk_comprobante_venta FOREIGN KEY (venta_id) REFERENCES ventas(id) ON DELETE CASCADE
);

CREATE TABLE devoluciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_devolucion VARCHAR(50) NOT NULL UNIQUE,
    venta_id BIGINT NOT NULL,
    cliente_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    fecha TIMESTAMP NOT NULL,
    motivo VARCHAR(500) NOT NULL,
    total NUMERIC(14,2) NOT NULL,
    estado VARCHAR(20) NOT NULL,
    CONSTRAINT fk_devolucion_venta FOREIGN KEY (venta_id) REFERENCES ventas(id),
    CONSTRAINT fk_devolucion_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id),
    CONSTRAINT fk_devolucion_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

CREATE TABLE detalles_devolucion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    devolucion_id BIGINT NOT NULL,
    producto_id BIGINT NOT NULL,
    cantidad INTEGER NOT NULL CHECK (cantidad > 0),
    monto NUMERIC(14,2) NOT NULL,
    CONSTRAINT fk_detalle_devolucion FOREIGN KEY (devolucion_id) REFERENCES devoluciones(id) ON DELETE CASCADE,
    CONSTRAINT fk_devolucion_producto FOREIGN KEY (producto_id) REFERENCES productos(id)
);

CREATE TABLE auditorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    accion VARCHAR(40) NOT NULL,
    entidad VARCHAR(100) NOT NULL,
    entidad_id VARCHAR(100),
    descripcion TEXT NOT NULL,
    valor_anterior TEXT,
    valor_nuevo TEXT,
    fecha TIMESTAMP NOT NULL,
    direccion_ip VARCHAR(60),
    CONSTRAINT fk_auditoria_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

CREATE INDEX idx_producto_nombre ON productos(nombre);
CREATE INDEX idx_producto_tipo ON productos(tipo_producto);
CREATE INDEX idx_lote_producto ON lotes(producto_id);
CREATE INDEX idx_lote_fecha ON lotes(fecha_ingreso);
CREATE INDEX idx_movimiento_producto ON movimientos_inventario(producto_id);
CREATE INDEX idx_movimiento_fecha ON movimientos_inventario(fecha);
CREATE INDEX idx_venta_fecha ON ventas(fecha);
CREATE INDEX idx_detalle_venta ON detalles_venta(venta_id);
CREATE INDEX idx_devolucion_venta ON devoluciones(venta_id);
CREATE INDEX idx_devolucion_fecha ON devoluciones(fecha);
CREATE INDEX idx_detalle_devolucion ON detalles_devolucion(devolucion_id);
CREATE INDEX idx_auditoria_usuario ON auditorias(usuario_id);
CREATE INDEX idx_auditoria_fecha ON auditorias(fecha);
CREATE INDEX idx_auditoria_accion ON auditorias(accion);
